# Site settings
title: 小信豬的原始部落
email: godleon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  從 <a href='http://godleon.blogspot.com' target='_blank'>Google Blogger</a> 搬過來囉!<p />
  記錄在 IT 方面學習的點點滴滴<p />
  一步一腳印朝 open source 的方向努力學習!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://godleon.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  godleon

# Build settings
#markdown: kramdown
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
